import { PieceStyle } from "../context/GameSettingsContext";

// In React Native, local images must be statically required.
const ASSETS: Record<Exclude<PieceStyle, "symbol">, Record<string, any>> = {
    "3d": {
        "wp": require("../../assets/pieces/3d/wp.png"),
        "wn": require("../../assets/pieces/3d/wn.png"),
        "wb": require("../../assets/pieces/3d/wb.png"),
        "wr": require("../../assets/pieces/3d/wr.png"),
        "wq": require("../../assets/pieces/3d/wq.png"),
        "wk": require("../../assets/pieces/3d/wk.png"),
        "bp": require("../../assets/pieces/3d/bp.png"),
        "bn": require("../../assets/pieces/3d/bn.png"),
        "bb": require("../../assets/pieces/3d/bb.png"),
        "br": require("../../assets/pieces/3d/br.png"),
        "bq": require("../../assets/pieces/3d/bq.png"),
        "bk": require("../../assets/pieces/3d/bk.png"),
    },
    "crystal": {
        "wp": require("../../assets/pieces/crystal/wp.png"),
        "wn": require("../../assets/pieces/crystal/wn.png"),
        "wb": require("../../assets/pieces/crystal/wb.png"),
        "wr": require("../../assets/pieces/crystal/wr.png"),
        "wq": require("../../assets/pieces/crystal/wq.png"),
        "wk": require("../../assets/pieces/crystal/wk.png"),
        "bp": require("../../assets/pieces/crystal/bp.png"),
        "bn": require("../../assets/pieces/crystal/bn.png"),
        "bb": require("../../assets/pieces/crystal/bb.png"),
        "br": require("../../assets/pieces/crystal/br.png"),
        "bq": require("../../assets/pieces/crystal/bq.png"),
        "bk": require("../../assets/pieces/crystal/bk.png"),
    },
    "glass": {
        "wp": require("../../assets/pieces/glass/wp.png"),
        "wn": require("../../assets/pieces/glass/wn.png"),
        "wb": require("../../assets/pieces/glass/wb.png"),
        "wr": require("../../assets/pieces/glass/wr.png"),
        "wq": require("../../assets/pieces/glass/wq.png"),
        "wk": require("../../assets/pieces/glass/wk.png"),
        "bp": require("../../assets/pieces/glass/bp.png"),
        "bn": require("../../assets/pieces/glass/bn.png"),
        "bb": require("../../assets/pieces/glass/bb.png"),
        "br": require("../../assets/pieces/glass/br.png"),
        "bq": require("../../assets/pieces/glass/bq.png"),
        "bk": require("../../assets/pieces/glass/bk.png"),
    },
    "wooden": {
        "wp": require("../../assets/pieces/wooden/wp.png"),
        "wn": require("../../assets/pieces/wooden/wn.png"),
        "wb": require("../../assets/pieces/wooden/wb.png"),
        "wr": require("../../assets/pieces/wooden/wr.png"),
        "wq": require("../../assets/pieces/wooden/wq.png"),
        "wk": require("../../assets/pieces/wooden/wk.png"),
        "bp": require("../../assets/pieces/wooden/bp.png"),
        "bn": require("../../assets/pieces/wooden/bn.png"),
        "bb": require("../../assets/pieces/wooden/bb.png"),
        "br": require("../../assets/pieces/wooden/br.png"),
        "bq": require("../../assets/pieces/wooden/bq.png"),
        "bk": require("../../assets/pieces/wooden/bk.png"),
    },
    "staunton": {
        "wp": require("../../assets/pieces/staunton/wp.png"),
        "wn": require("../../assets/pieces/staunton/wn.png"),
        "wb": require("../../assets/pieces/staunton/wb.png"),
        "wr": require("../../assets/pieces/staunton/wr.png"),
        "wq": require("../../assets/pieces/staunton/wq.png"),
        "wk": require("../../assets/pieces/staunton/wk.png"),
        "bp": require("../../assets/pieces/staunton/bp.png"),
        "bn": require("../../assets/pieces/staunton/bn.png"),
        "bb": require("../../assets/pieces/staunton/bb.png"),
        "br": require("../../assets/pieces/staunton/br.png"),
        "bq": require("../../assets/pieces/staunton/bq.png"),
        "bk": require("../../assets/pieces/staunton/bk.png"),
    },
    "california": {
        "wp": require("../../assets/pieces/california/wp.png"),
        "wn": require("../../assets/pieces/california/wn.png"),
        "wb": require("../../assets/pieces/california/wb.png"),
        "wr": require("../../assets/pieces/california/wr.png"),
        "wq": require("../../assets/pieces/california/wq.png"),
        "wk": require("../../assets/pieces/california/wk.png"),
        "bp": require("../../assets/pieces/california/bp.png"),
        "bn": require("../../assets/pieces/california/bn.png"),
        "bb": require("../../assets/pieces/california/bb.png"),
        "br": require("../../assets/pieces/california/br.png"),
        "bq": require("../../assets/pieces/california/bq.png"),
        "bk": require("../../assets/pieces/california/bk.png"),
    },
    "merida": {
        "wp": require("../../assets/pieces/merida/wp.png"),
        "wn": require("../../assets/pieces/merida/wn.png"),
        "wb": require("../../assets/pieces/merida/wb.png"),
        "wr": require("../../assets/pieces/merida/wr.png"),
        "wq": require("../../assets/pieces/merida/wq.png"),
        "wk": require("../../assets/pieces/merida/wk.png"),
        "bp": require("../../assets/pieces/merida/bp.png"),
        "bn": require("../../assets/pieces/merida/bn.png"),
        "bb": require("../../assets/pieces/merida/bb.png"),
        "br": require("../../assets/pieces/merida/br.png"),
        "bq": require("../../assets/pieces/merida/bq.png"),
        "bk": require("../../assets/pieces/merida/bk.png"),
    },
    "uscf": {
        "wp": require("../../assets/pieces/uscf/wp.png"),
        "wn": require("../../assets/pieces/uscf/wn.png"),
        "wb": require("../../assets/pieces/uscf/wb.png"),
        "wr": require("../../assets/pieces/uscf/wr.png"),
        "wq": require("../../assets/pieces/uscf/wq.png"),
        "wk": require("../../assets/pieces/uscf/wk.png"),
        "bp": require("../../assets/pieces/uscf/bp.png"),
        "bn": require("../../assets/pieces/uscf/bn.png"),
        "bb": require("../../assets/pieces/uscf/bb.png"),
        "br": require("../../assets/pieces/uscf/br.png"),
        "bq": require("../../assets/pieces/uscf/bq.png"),
        "bk": require("../../assets/pieces/uscf/bk.png"),
    },
    "cardinal": {
        "wp": require("../../assets/pieces/cardinal/wp.png"),
        "wn": require("../../assets/pieces/cardinal/wn.png"),
        "wb": require("../../assets/pieces/cardinal/wb.png"),
        "wr": require("../../assets/pieces/cardinal/wr.png"),
        "wq": require("../../assets/pieces/cardinal/wq.png"),
        "wk": require("../../assets/pieces/cardinal/wk.png"),
        "bp": require("../../assets/pieces/cardinal/bp.png"),
        "bn": require("../../assets/pieces/cardinal/bn.png"),
        "bb": require("../../assets/pieces/cardinal/bb.png"),
        "br": require("../../assets/pieces/cardinal/br.png"),
        "bq": require("../../assets/pieces/cardinal/bq.png"),
        "bk": require("../../assets/pieces/cardinal/bk.png"),
    }
};

export const getPieceAssetSource = (color: string, type: string, style: PieceStyle) => {
    if (style === "symbol") {
        return null;
    }

    const key = `${color}${type}`.toLowerCase();
    
    return ASSETS[style][key] || null;
};
